---
title: "Resume"
output: html_document
hidedate: true
hiderelated: true
hidediscus: true
---
Sarai Rainey 
169 N Hazelwood Dr Mocksville, NC 27028| (956)352-9930 | sarai06286@gmail.com

Sarai Rainey was born February 10, 1999 in Mission, Tx. From early on she held a strong passion for music, playing the trumpet up until college, while being the first chair throughout high school for Rio Grande City Highschool. However, her interests moved towards anatomy, thanks to the popular tv series "Bones", and sustainability. She is now on her way to graduating from the University of Texas at Austin with a BSA in biology. This is followed by a gap year as a Pharmacy Technician at Walgreens while also having a Depop shop selling second hand clothing items at an affordable right to people all over the world, including Swedin and the UK. 

Education

BSA-Biology, University of Texas at Austin
Certificate in Forensic Science

Work Experience

Wendys
Cashier | Austin, TX | September 2017-May 2018
Assisted food prep workers by taking customer orders, bagging up their meals, and preparing any requested specialty drinks. Worked to remember names of regular customers along with their orders.

The Office Bar and Grill
Server | McAllen, TX | June 2018-August 2018
Built guest loyalty by remembering customer names, orders, and recommending popular meal items. Catered to large parties, detail cleaned the food service area, and assisted bar tenders during high-volume shifts.

Cabo Bobs
Cashier, Food Line Server | Austin, TX | September 2018- December 2020
Developed strong relationships with coworkers while taught manager skills to lead our group during high-volume shifts. Assisted customers’ orders and resolved any issues with orders.

Walgreens
Pharmacy Technician | Mocksville, NC | May 2021-Present

Organization Experience


Christian Students on Campus, Member 2017, Field Intern 2018

Skills


•	Active Listening
•	Attention to Detail
•	Ability to Work Under Pressure
•	Strong Interpersonal Skills

<center>
<iframe src="/resume.pdf" width="100%" height="800" border="0"></iframe>
</center>
